version: '3.8'

services:
  bot:
    build: .
    container_name: nasa-space-explorer-bot
    restart: always
    depends_on:
      - redis
      - prometheus
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - NASA_API_KEY=${NASA_API_KEY}
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./logs:/app/logs
      - ./config.py:/app/config.py:ro
    networks:
      - bot-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8000:8000"

  redis:
    image: redis:7-alpine
    container_name: nasa-redis
    restart: always
    volumes:
      - redis-data:/data
    networks:
      - bot-network

  prometheus:
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"
    networks:
      - bot-network

  grafana:
    image: grafana/grafana:latest
    restart: always
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  redis-data:
  prometheus-data:
  grafana-data:
